# Generated by Django 3.2.2 on 2021-05-07 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(help_text='Zadejte podkategorii', max_length=50, unique=True, verbose_name='Název kategorie')),
                ('oblast', models.CharField(blank=True, choices=[('Beletrie', 'beletrie'), ('Poezie', 'poezie'), ('Historická literatura', 'historicka_literatura'), ('Literatura pro děti a mládež', 'deti_literatura'), ('Odborná literatura', 'odborna_literatura'), ('Naučná literatura', 'naucna_literatura'), ('Kuchařky', 'kucharky'), ('Cestování', 'cestovani'), ('Zdraví', 'zdravi')], default='Beletrie', max_length=50, verbose_name='Kategorie')),
            ],
            options={
                'verbose_name': 'Kategorie',
                'ordering': ['typ'],
            },
        ),
        migrations.CreateModel(
            name='kniha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=50, verbose_name='Název knihy')),
                ('autor_jmeno', models.CharField(max_length=50, verbose_name='Jméno autora')),
                ('autor_prijmeni', models.CharField(max_length=50, verbose_name='Jméno autora')),
                ('rok', models.DateField(auto_now_add=True)),
                ('popis', models.TextField(blank=True, null=True, verbose_name='Popis knihy')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='knihy/%Y/%m/%d', verbose_name='Foto knihy')),
                ('kategorie', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='books.kategorie')),
            ],
            options={
                'verbose_name': 'Knihy',
                'ordering': ['nazev', '-rok'],
            },
        ),
    ]
