# Generated by Django 3.2.2 on 2021-05-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210507_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kniha',
            name='autor_prijmeni',
            field=models.CharField(max_length=50, verbose_name='Příjmení autora'),
        ),
    ]
