# Generated by Django 3.2.2 on 2021-05-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_kniha_autor_prijmeni'),
    ]

    operations = [
        migrations.AddField(
            model_name='kniha',
            name='hodnoceni',
            field=models.IntegerField(blank=True, choices=[(5, 'Výborná'), (4, 'Zabaví'), (3, 'Průměrná'), (2, 'Špatná'), (1, 'Velmi špatná')], default=3, help_text='Vyberte označení stavu', verbose_name='Hodnocení'),
        ),
    ]
